### PR TITLE
Rev C

### PR DESCRIPTION
**Pull request by nealjack**
Fix issues from Rev B listed in #2. Reroute upper left corner of board to move temp, humidity, and pressure sensors closer to edge, and make room for IC labels.

### CODE REVIEW

**Comment by nealjack** [comment]
Branden mentioned that some ICs might need to be replaced. The digital accelerometer and the illuminance sensor are no longer in production.

this is gonna suck

**Comment by nealjack** [comment]
The ICM-20948 is a drop in replacement for the MPU-9250, however it has a max VDDIO of 1.95, meaning it will need an LDO and level shifters.

The TI OPT300X looks like a good alternative to the MAX44009.

**Comment by brghena** [comment]
You've got free reign to make changes as you see fit. The light sensor was always optional and could be left out entirely as it's not used in labs. Technically you only need to replace the MPU-9250 with a gyro, as the analog accelerometer exists, but it's probably good to get a 9DOF I2C sensor on there for student projects. You don't have to stick with the same one or the same family though.

**Comment by brghena** [comment]
Notes
 * I think you have "Hi" and "Lo" backwards on the switch label.
 * Be advised that if you fix RX and TX for the Kobuki, you'll need to change the software too. Which means that you will definitely need a different board file for Buckler revB, and the same examples won't work on both. Might be safer to just leave it alone at this point.

**Comment by nealjack** [comment]
Would it be a terrible idea to just see if GT Han or another fab can source the non-stocked components? Like just try to get a quote and see what happens? If they come back and say we can't get this part, then do a redesign?

Changing parts and resulting software drivers is going to cause a pretty big rift in software support for the two existing versions of buckler (A + B).

**Comment by brghena** [comment]
It's not a bad idea. When a professor at DePaul made Bucklers in December, they used that method and it worked. However, they were only making 4 boards. It will also result in more delay, as you've got to do a back-and-forth.

Also, I would make sure that you're clear that the ICMxxxx is not a valid replacement for the MPU-9250 so they don't make that mistake.

**Comment by brghena** [comment]
It should also be possible to have an automatic configuration that determines if a Buckler revB or revC is in use. Something like reading the ID on the accelerometer chip, for instance.

**Comment by nealjack** [comment]
@brghena I think I fixed up the BOM issues. Can you check before I send out for quotes?

**Comment by brghena** [comment]
You've got 'J#" and 'JP#' parts. Probably want to consolidate them into one or the other and renumber.

**Comment by nealjack** [comment]
@brghena Okay, I swapped out the accelerometer and light sensor. Do you have one more review in you?

**Comment by brghena** [comment]
This looks good to me!

**Comment by nealjack** [comment]
I'm going to merge this pull request in a few hours unless anyone else has any feedback. Most recently, I just added a driver for the new digital accelerometer. I still need to add a driver for the new light sensor.

**Pull request merged**
